packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: false
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - "@techsquidtv/gifenc@1.1.0"

allowBuilds:
  "@sentry/cli": true
  esbuild: true
  sharp: true
  workerd: true

overrides:
  baseline-browser-mapping: 2.10.31
  enhanced-resolve: 5.21.3
  es-object-atoms: 1.1.1

peerDependencyRules:
  ignoreMissing:
    - mssql
    - "@types/mssql"
