/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersConnectRouteImport } from './routes/providers.connect'
import { Route as AppSourcesRouteImport } from './routes/_app.sources'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AuthPlexCompleteRouteImport } from './routes/auth.plex.complete'
import { Route as AppEditSessionIdRouteImport } from './routes/_app.edit.$sessionId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersConnectRoute = ProvidersConnectRouteImport.update({
  id: '/providers/connect',
  path: '/providers/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AuthPlexCompleteRoute = AuthPlexCompleteRouteImport.update({
  id: '/auth/plex/complete',
  path: '/auth/plex/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEditSessionIdRoute = AppEditSessionIdRouteImport.update({
  id: '/edit/$sessionId',
  path: '/edit/$sessionId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/sources': typeof AppSourcesRoute
  '/providers/connect': typeof ProvidersConnectRoute
  '/edit/$sessionId': typeof AppEditSessionIdRoute
  '/auth/plex/complete': typeof AuthPlexCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/sources': typeof AppSourcesRoute
  '/providers/connect': typeof ProvidersConnectRoute
  '/edit/$sessionId': typeof AppEditSessionIdRoute
  '/auth/plex/complete': typeof AuthPlexCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/sources': typeof AppSourcesRoute
  '/providers/connect': typeof ProvidersConnectRoute
  '/_app/edit/$sessionId': typeof AppEditSessionIdRoute
  '/auth/plex/complete': typeof AuthPlexCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sources'
    | '/providers/connect'
    | '/edit/$sessionId'
    | '/auth/plex/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sources'
    | '/providers/connect'
    | '/edit/$sessionId'
    | '/auth/plex/complete'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/sources'
    | '/providers/connect'
    | '/_app/edit/$sessionId'
    | '/auth/plex/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ProvidersConnectRoute: typeof ProvidersConnectRoute
  AuthPlexCompleteRoute: typeof AuthPlexCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/connect': {
      id: '/providers/connect'
      path: '/providers/connect'
      fullPath: '/providers/connect'
      preLoaderRoute: typeof ProvidersConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/plex/complete': {
      id: '/auth/plex/complete'
      path: '/auth/plex/complete'
      fullPath: '/auth/plex/complete'
      preLoaderRoute: typeof AuthPlexCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/edit/$sessionId': {
      id: '/_app/edit/$sessionId'
      path: '/edit/$sessionId'
      fullPath: '/edit/$sessionId'
      preLoaderRoute: typeof AppEditSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppEditSessionIdRoute: typeof AppEditSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppEditSessionIdRoute: AppEditSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ProvidersConnectRoute: ProvidersConnectRoute,
  AuthPlexCompleteRoute: AuthPlexCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
